USE llantas;
INSERT INTO IndiceCarga (id, capacidad) VALUES (65,290);
INSERT INTO IndiceCarga (id, capacidad) VALUES (66,300);
INSERT INTO IndiceCarga (id, capacidad) VALUES (67,307);
INSERT INTO IndiceCarga (id, capacidad) VALUES (68,315);
INSERT INTO IndiceCarga (id, capacidad) VALUES (69,325);
INSERT INTO IndiceCarga (id, capacidad) VALUES (70,335);
INSERT INTO IndiceCarga (id, capacidad) VALUES (71,345);
INSERT INTO IndiceCarga (id, capacidad) VALUES (72,355);
INSERT INTO IndiceCarga (id, capacidad) VALUES (73,365);
INSERT INTO IndiceCarga (id, capacidad) VALUES (74,375);
INSERT INTO IndiceCarga (id, capacidad) VALUES (75,387);
INSERT INTO IndiceCarga (id, capacidad) VALUES (76,400);
INSERT INTO IndiceCarga (id, capacidad) VALUES (77,412);
INSERT INTO IndiceCarga (id, capacidad) VALUES (78,425);
INSERT INTO IndiceCarga (id, capacidad) VALUES (79,437);
INSERT INTO IndiceCarga (id, capacidad) VALUES (80,450);
INSERT INTO IndiceCarga (id, capacidad) VALUES (81,462);
INSERT INTO IndiceCarga (id, capacidad) VALUES (82,475);
INSERT INTO IndiceCarga (id, capacidad) VALUES (83,487);
INSERT INTO IndiceCarga (id, capacidad) VALUES (84,500);
INSERT INTO IndiceCarga (id, capacidad) VALUES (85,515);
INSERT INTO IndiceCarga (id, capacidad) VALUES (86,530);
INSERT INTO IndiceCarga (id, capacidad) VALUES (87,545);
INSERT INTO IndiceCarga (id, capacidad) VALUES (88,560);
INSERT INTO IndiceCarga (id, capacidad) VALUES (89,580);
INSERT INTO IndiceCarga (id, capacidad) VALUES (90,600);
INSERT INTO IndiceCarga (id, capacidad) VALUES (91,615);
INSERT INTO IndiceCarga (id, capacidad) VALUES (92,630);
INSERT INTO IndiceCarga (id, capacidad) VALUES (93,650);
INSERT INTO IndiceCarga (id, capacidad) VALUES (94,670);
INSERT INTO IndiceCarga (id, capacidad) VALUES (95,690);
INSERT INTO IndiceCarga (id, capacidad) VALUES (96,710);
INSERT INTO IndiceCarga (id, capacidad) VALUES (97,730);
INSERT INTO IndiceCarga (id, capacidad) VALUES (98,750);
INSERT INTO IndiceCarga (id, capacidad) VALUES (99,775);
INSERT INTO IndiceCarga (id, capacidad) VALUES (100,800);
INSERT INTO IndiceCarga (id, capacidad) VALUES (101,825);
INSERT INTO IndiceCarga (id, capacidad) VALUES (102,850);
INSERT INTO IndiceCarga (id, capacidad) VALUES (103,875);
INSERT INTO IndiceCarga (id, capacidad) VALUES (104,900);
INSERT INTO IndiceCarga (id, capacidad) VALUES (105,925);
INSERT INTO IndiceCarga (id, capacidad) VALUES (106,950);
INSERT INTO IndiceCarga (id, capacidad) VALUES (107,975);
INSERT INTO IndiceCarga (id, capacidad) VALUES (108,1000);
INSERT INTO IndiceCarga (id, capacidad) VALUES (109,1030);
INSERT INTO IndiceCarga (id, capacidad) VALUES (110,1060);
INSERT INTO IndiceCarga (id, capacidad) VALUES (111,1090);
INSERT INTO IndiceCarga (id, capacidad) VALUES (112,1120);
INSERT INTO IndiceCarga (id, capacidad) VALUES (113,1150);
INSERT INTO IndiceCarga (id, capacidad) VALUES (114,1180);
INSERT INTO IndiceCarga (id, capacidad) VALUES (115,1215);
INSERT INTO IndiceCarga (id, capacidad) VALUES (116,1250);
INSERT INTO IndiceCarga (id, capacidad) VALUES (117,1285);
INSERT INTO IndiceCarga (id, capacidad) VALUES (118,1320);
INSERT INTO IndiceCarga (id, capacidad) VALUES (119,1360);
INSERT INTO IndiceCarga (id, capacidad) VALUES (120,1400);
INSERT INTO IndiceCarga (id, capacidad) VALUES (121,1450);
INSERT INTO IndiceCarga (id, capacidad) VALUES (122,1500);
INSERT INTO IndiceCarga (id, capacidad) VALUES (123,1550);
INSERT INTO IndiceCarga (id, capacidad) VALUES (124,1600);
INSERT INTO IndiceCarga (id, capacidad) VALUES (125,1650);
INSERT INTO IndiceCarga (id, capacidad) VALUES (126,1700);
INSERT INTO IndiceCarga (id, capacidad) VALUES (127,1750);
INSERT INTO IndiceCarga (id, capacidad) VALUES (128,1800);
INSERT INTO IndiceCarga (id, capacidad) VALUES (129,1850);
INSERT INTO IndiceVelocidad (codigo, descripcion, velocidadMaxima) VALUES ('L', 'Fuera de Carretera y Camiones Ligeros', 120);
INSERT INTO IndiceVelocidad (codigo, descripcion, velocidadMaxima) VALUES ('M', 'Llanta de Repuesto Temporal', 130);
INSERT INTO IndiceVelocidad (codigo, descripcion, velocidadMaxima) VALUES ('N', 'Llanta de Repuesto Temporal', 140);
INSERT INTO IndiceVelocidad (codigo, descripcion, velocidadMaxima) VALUES ('Q', 'Invierno 4x4', 160);
INSERT INTO IndiceVelocidad (codigo, descripcion, velocidadMaxima) VALUES ('R', 'Camioneta de Trabajo Pesado / Camiones Ligeros', 170);
INSERT INTO IndiceVelocidad (codigo, descripcion, velocidadMaxima) VALUES ('S', 'Sedan Familiar y Vans', 180);
INSERT INTO IndiceVelocidad (codigo, descripcion, velocidadMaxima) VALUES ('T', 'Sedan Familiar y Vans', 190);
INSERT INTO IndiceVelocidad (codigo, descripcion, velocidadMaxima) VALUES ('H', 'Sedanes Deportivos y Cupés', 210);
INSERT INTO IndiceVelocidad (codigo, descripcion, velocidadMaxima) VALUES ('V', 'Carros Deportivos', 240);
INSERT INTO IndiceVelocidad (codigo, descripcion, velocidadMaxima) VALUES ('Z', 'Carros Deportivos', 250);
INSERT INTO IndiceVelocidad (codigo, descripcion, velocidadMaxima) VALUES ('W', 'Carros Deportivos Exóticos', 270);
INSERT INTO IndiceVelocidad (codigo, descripcion, velocidadMaxima) VALUES ('Y', 'Carros Deportivos Exóticos', 300);
INSERT INTO IndiceVelocidad (codigo, descripcion, velocidadMaxima) VALUES ('(Y)', 'Carros Deportivos Exóticos', 310);